language: ruby
sudo: true
dist: trusty
rvm:
- 2.5.3
env:
  global:
  - JEKYLL_ENV=production

script:
  - npm install -g bower
  - bower install
  - gem install bundler
  - bundle exec jekyll build

after_success:
  - ssh-keyscan -H named-data.net 2>&1 | tee -a $HOME/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_1ff95cb1103a_key -iv $encrypted_1ff95cb1103a_iv -in .travis.d/id-rsa.enc -out .travis.d/id-rsa -d
  - mkdir -p ~/.ssh && mv .travis.d/id-rsa ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - rsync -arv --progress --delete _site/ ndn-cri@named-data.net:/var/www/named-data.net/cri
