safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache']

plugins:
  - jekyll-assets

url: https://cri.named-data.net
baseurl:

# Configuration for site
title: Building the Core NDN Infrastructure to Advance Information-Centric Networking Research (NDN-CRI)
logo_title: NDN-CRI Project
author: NDN-CRI Project Team
email:
logo:

google_analytics: "UA-22320603-7"
  
navbar_list:
- name: Home
  link: /
# - name: Meetings
#   link: meetings.html
- name: Activities
  link: activities.html
- name: Software
  link: software.html
- name: Testbed
  link: testbed.html
- name: Publications
  link: pub.html
- name: Team
  link: team.html

assets:
  cache: .sass-cache

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
